backend:
  name: github
  repo: [USER_NAME]/[REPO_NAME] # استبدل هذه باسم مستخدمك واسم المستودع
  branch: main

media_folder: "images" # المجلد الذي ستحفظ فيه الصور
public_folder: "/images"

collections:
  - name: "blog"
    label: "الأخبار"
    folder: "content/posts" # هنا سيتم حفظ المقالات كملفات نصية
    create: true
    fields:
      - {label: "العنوان", name: "title", widget: "string"}
      - {label: "تاريخ النشر", name: "date", widget: "datetime"}
      - {label: "الصورة", name: "image", widget: "image"}
      - {label: "المحتوى", name: "body", widget: "markdown"}
