backend:
  name: github
  repo: 3dotokk/Czeal
  branch: main

media_folder: "images"
public_folder: "/images"

collections:
  - name: "blog"
    label: "الأخبار"
    folder: "content/posts"
    create: true
    fields:
      - {label: "العنوان", name: "title", widget: "string"}
      - {label: "تاريخ النشر", name: "date", widget: "datetime"}
      - {label: "الصورة", name: "image", widget: "image"}
      - {label: "المحتوى", name: "body", widget: "markdown"}
