name: Czeal AI Auto Publisher
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install google-generativeai

      - name: Run Script
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: python generate.py

      - name: Push Changes
        run: |
          git config --global user.name 'Czeal-Bot'
          git config --global user.email 'bot@czeal.com'
          git add index.html
          git commit -m "🤖 AI Update" || exit 0
          git push
